# netlify.toml

[build]
  command = "npm run build"
  publish = "out"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[headers]
  # Cache rules for static assets
  "/static/*"
  Cache-Control = "public, max-age=31536000, immutable"

  # Cache rules for other assets
  "/*.js"
  Cache-Control = "public, max-age=0, must-revalidate"
  "/*.css"
  Cache-Control = "public, max-age=0, must-revalidate"
